name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload reports
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: reports
        # A file, directory or wildcard pattern that describes what to upload
        path: "**/build/reports/*"
    - name: Upload apks
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: apks
        # A file, directory or wildcard pattern that describes what to upload
        path: "**/build/outputs/apk/release/*"
